# Generated by Django 3.2.9 on 2021-11-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20211126_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Google',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
